# Generated by Django 3.1.2 on 2020-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-put_date',)},
        ),
    ]
